### ISSUE TITLE
Header not appearing correctly

### ISSUE THREAD

**Issue by dowcet** [punchagan/resume#3]
Instead of a name and address and all that at the top of my PDF, I get "{{HEADER}}" and the date, with a lot of blank space. Any suggestions?

**Comment by punchagan** [comment]
- Do you have `personal-info.org` setup correctly? 
- What version of org-mode, emacs do you use?

**Comment by dowcet** [comment]
Initially I left `personal-info.org` alone. Then I tried playing with it, but nothing I tried changed the output.

Emacs 24.3.1, Org-Mode 7.9.3f

**Comment by punchagan** [comment]
Org-Mode 7.9.3f is pretty old. I would recommend you try with a newer version.

**Comment by dowcet** [comment]
I upgraded to 8.2.10. Now I get "Resume" instead of "{{Header}}". If I change anything in `personal-info.org` then I also get a LaTeX tag, and curly braces all over the place.

**Comment by dowcet** [comment]
I think there is probably a problem with my org-mode installation so I will close this for now.
